const questions=[
 {title:'Como está sua experiência com consórcio?',options:[['Ainda estou começando.','base',3],['Já atendo, mas ainda improviso bastante.','routine',2],['Já vendo e quero organizar meu processo.','routine',1],['Tenho uma rotina e quero aperfeiçoá-la.','advanced',2]]},
 {title:'Como chegam suas oportunidades hoje?',options:[['Ainda não sei onde encontrar clientes.','prospecting',3],['Dependo quase só de indicações.','prospecting',2],['Publico nas redes, mas gero poucas conversas.','digital',3],['Uso mais de um canal com regularidade.','advanced',1]]},
 {title:'Quando alguém pede uma simulação, o que você faz?',options:[['Envio uma tabela ou parcela logo de início.','diagnosis',3],['Faço algumas perguntas, mas sem roteiro.','diagnosis',2],['Entendo objetivo, prazo e capacidade antes.','advanced',1],['Ainda não sei como conduzir esse atendimento.','diagnosis',3]]},
 {title:'O cliente diz “vou pensar”. Qual é o seu próximo passo?',options:[['Espero que ele volte a falar comigo.','followup',3],['Mando mensagem quando lembro.','followup',2],['Registro a dúvida e combino uma retomada.','advanced',1],['Tenho dificuldade para entender o que travou.','diagnosis',2]]},
 {title:'O que você mais quer desenvolver agora?',options:[['Encontrar clientes e gerar conversas.','prospecting',4],['Atender e apresentar propostas com clareza.','diagnosis',4],['Acompanhar oportunidades e organizar a rotina.','routine',4],['Usar o Instagram para atrair oportunidades.','digital',4]]}
];
const profiles={
 base:{title:'Seu próximo passo: construir a base.',body:'Uma sequência clara pode ajudar você a começar com mais direção: entender o cliente, conhecer o processo e preparar sua rotina.',action:'Comece pela Parte 1. Depois, use o roteiro de diagnóstico para preparar suas primeiras conversas.',parts:'Partes 1 e 4 · A cabeça do vendedor e Atendimento e diagnóstico'},
 prospecting:{title:'Seu próximo passo: organizar a prospecção.',body:'Suas respostas apontam espaço para ampliar e organizar as fontes de oportunidades. Definir canais e uma rotina ajuda a sair da dependência de contatos ocasionais.',action:'Escolha um canal para trabalhar com regularidade e registre as conversas iniciadas. Consulte o plano de conteúdo para organizar os temas.',parts:'Partes 2 e 3 · Onde encontrar clientes e Instagram que vende'},
 digital:{title:'Seu próximo passo: conectar conteúdo e conversa.',body:'A presença digital é uma prioridade para você. O foco pode ser deixar mais claro quem você ajuda e como o conteúdo abre uma conversa com possíveis clientes.',action:'Revise sua apresentação no perfil e escolha temas ligados às dúvidas reais dos clientes. Use o plano de conteúdo como ponto de partida.',parts:'Parte 3 + conteúdo complementar · Instagram que vende consórcio'},
 diagnosis:{title:'Seu próximo passo: aprofundar o diagnóstico.',body:'Antes da proposta, vale entender melhor o objetivo, o prazo e a capacidade do cliente. Suas respostas sugerem que essa etapa merece atenção.',action:'Use o roteiro de diagnóstico em sua próxima conversa. Registre o objetivo do cliente e confira o checklist antes de enviar a proposta.',parts:'Partes 4 e 5 · Atendimento e diagnóstico e A venda e o fechamento'},
 followup:{title:'Seu próximo passo: dar continuidade às conversas.',body:'Suas respostas indicam uma oportunidade de estruturar o acompanhamento. Retomar com contexto ajuda você a saber qual é a próxima ação de cada atendimento.',action:'Registre o motivo da pausa e combine o próximo contato. Consulte os scripts e adapte a retomada à conversa anterior.',parts:'Partes 6 e 10 · Follow-up e reativação e Sistema operacional'},
 routine:{title:'Seu próximo passo: transformar esforço em rotina.',body:'Você pode se beneficiar de uma agenda comercial mais definida, com espaço para prospectar, responder, acompanhar propostas e revisar as atividades.',action:'Reserve blocos de tempo para as principais atividades e registre o próximo passo de cada oportunidade. Revise a semana antes de começar outra.',parts:'Partes 9 e 10 · Máquina comercial e Sistema operacional'},
 advanced:{title:'Seu próximo passo: aperfeiçoar o processo.',body:'Você já relata hábitos de organização e atendimento consultivo. O material pode apoiar a revisão dos pontos que ainda precisam de mais consistência.',action:'Revise seu acompanhamento de oportunidades e escolha um indicador para observar. Use os modelos para avaliar o que pode ficar mais claro.',parts:'Partes 5, 6 e 10 · Propostas, acompanhamento e rotina'}
};

function calculateProfile(answers){const scores=Object.fromEntries(Object.keys(profiles).map(k=>[k,0]));answers.forEach((a,i)=>{const [,key,weight]=questions[i].options[a];scores[key]+=weight});const preferred=questions[questions.length-1].options[answers[questions.length-1]][1];return Object.keys(scores).sort((a,b)=>scores[b]-scores[a]||(a===preferred?-1:b===preferred?1:0))[0]}
